language: go

go:
  - "1.10"

install:
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - golint -set_exit_status ./cmd/... ./internal/types/
  - go test -v ./...
