apiVersion: v1
kind: Pod
metadata:
  name: cpupod-exclusive
  annotations:
    nokia.k8s.io/cpus: |
      [{
      "container": "cputest-exclusive",
      "processes":
        [{
           "process": "/bin/sh",
           "args": ["-c","/thread_busyloop -n \"Process \"cputest-exclusive"],
           "cpus": 3,
           "pool": "exclusive-pool"
         } 
      ]
      }]
spec:
  containers:
  - name: cputest-exclusive
    image: busyloop
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
