apiVersion: v1
kind: ConfigMap
metadata:
  name: cpu-pooler-configmap
data:
  poolconfig-controller.yaml: |
    pools: 
      exclusive-pool:
        cpus : "4,5"
      exclusive-pool-2:
        cpus : "2,3"
      shared-pool:
        cpus : "1"
    nodeSelector:
      nodeType: controller
  poolconfig-dpdk.yaml: |
    pools: 
      exclusive-pool:
        cpus : "2,3,4,5,6,7"
      shared-pool:
        cpus : "1"
    nodeSelector:
      nodeType: dpdk
