apiVersion: v1
kind: ConfigMap
metadata:
  name: cpu-pooler-configmap
  namespace: kube-system
data:
  poolconfig-controller.yaml: |
    pools: 
      exclusive-pool-cloudphon-1e:
        cpus : "64-127"
        hyperThreadingPolicy: singleThreaded
        overcommitment: 3
      exclusive-pool:
        cpus : "4,5"
        hyperThreadingPolicy: singleThreaded
      exclusive-pool-cloudphone-2:
        cpus : "64-127"
        hyperThreadingPolicy: multiThreaded
      shared-pool:
        cpus : "10-63"
      default:
        cpus: "0"
    nodeSelector:
      #node-role.kubernetes.io/node: 
      kubernetes.io/hostname: xxx
