apiVersion: v1
kind: Pod
metadata:
  name: cpupod-exclusive
spec:
  containers:
  - name: cputest-exclusive
    image: busyloop
    command: [ /thread_busyloop ]
    args: ["-c","$(EXCLUSIVE_CPUS)","-s","$(SHARED_CPUS)","-n 'Process cputest-exclusive'"]
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: 2000Mi
        nokia.k8s.io/exclusive-pool: "2"
        nokia.k8s.io/shared-pool: "500"
      limits:
        memory: 2000Mi
        nokia.k8s.io/exclusive-pool: "2"
        nokia.k8s.io/shared-pool: "500"

