apiVersion: v1
kind: Pod
metadata:
  name: cpupod
  annotations:
    nokia.k8s.io/cpus: |
      [{
      "container": "exclusivetestcontainer",
      "processes":
        [{
           "process": "/bin/sh",
           "args": ["-c","/thread_busyloop -n \"Process \"1"],
           "cpus": 1,
           "pool": "exclusive-pool"
         },
         {
           "process": "/bin/sh",
           "args": ["-c", "/thread_busyloop -n \"Process \"2"],
           "pool": "exclusive-pool",
           "cpus": 1
         } 
      ]
      }]
spec:
  containers:
  - name: sharedtestcontainer
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 1; done;" ]
    image: busyloop
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: 2000Mi
        nokia.k8s.io/shared-pool: "160"
      limits:
        nokia.k8s.io/shared-pool: "160"
        memory: 2000Mi
  - name: exclusivetestcontainer
    image: busyloop
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 1; done;" ]
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 2000Mi
        nokia.k8s.io/exclusive-pool: "2"
      limits:
        memory: 2000Mi
        nokia.k8s.io/exclusive-pool: "2"
  - name: defaulttestcontainer
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 1; done;" ]
    image: busyloop
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
