apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpu-setter
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caas:cpu-setter
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: caas:cpu-setter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: caas:cpu-setter
subjects:
- kind: ServiceAccount
  name: cpu-setter
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: caas:cpu-setter-psp
subjects:
- kind: ServiceAccount
  name: cpu-setter
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: caas:infra-psp
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cpu-setter
  namespace: kube-system
  labels:
    cpu-pooler: cpu-setter
spec:
  selector:
    matchLabels:
      cpu-pooler: cpu-setter
  template:
      labels:
        cpu-pooler: cpu-setter
    spec:
      containers:
      - name: cpu-device-plugin
        image: cpusetter
        imagePullPolicy: IfNotPresent
        ##--cpusetroot needs to be set to the root of the cgroupfs hierarchy used by Kubelet for workloads
        command: [ "/cpu-setter", "--poolconfigs=/etc/cpu-pooler", "--cpusetroot=/sys/fs/cgroup/cpuset/kubepods/" ]
        volumeMounts:
         - mountPath: /etc/cpu-pooler
           name: cpu-pooler-config
         - mountPath: /var/lib/kubelet/device-plugins/kubelet_internal_checkpoint
           name: checkpointfile
           readOnly: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      ## CPUSetter parses the Kubelet checkpoint file for Device allocations
      - name: checkpointfile
        hostPath:
         path: /var/lib/kubelet/device-plugins/kubelet_internal_checkpoint
      ## The pool configuration files need to be mounted here
      - name: cpu-pooler-config
        configMap:
          name: cpu-pooler-configmap
      serviceAccountName: cpu-setter
