apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpu-setter
  namespace: kube-plugins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caas:cpu-setter
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: caas:cpu-setter-kube-plugins  # 新上线
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: caas:cpu-setter
subjects:
- kind: ServiceAccount
  name: cpu-setter
  namespace: kube-plugins
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cpu-setter
  namespace: kube-plugins
  labels:
    cpu-pooler: cpu-setter
spec:
  selector:
    matchLabels:
      cpu-pooler: cpu-setter
  template:
    metadata:
      labels:
        cpu-pooler: cpu-setter
    spec:
      hostNetwork: true
      imagePullSecrets:
        - name: regcred
      containers:
      - name: cpu-device-plugin
        image: 100.76.9.59:8888/cloudphone/cph-cpusetter:v0.0.0.12
        imagePullPolicy: IfNotPresent
        ##--cpusetroot needs to be set to the root of the cgroupfs hierarchy used by Kubelet for workloads
        command: [ "/cpusetter", "--poolconfigs=/etc/cpu-pooler", "--cpusetroot=/rootfs/sys/fs/cgroup/cpuset/kubepods", "--cpuroot=/rootfs/sys/devices/system/cpu"]
        resources:
          requests:
            cpu: "10m"
        volumeMounts:
         - name: time-mount
           mountPath: /etc/localtime
           readOnly: true
         - mountPath: /etc/cpu-pooler
           name: cpu-pooler-config
        ## -- do not mount kubepods under /sys to avoid circular linking
         - mountPath: /sys/devices/system/cpu/
           name: system-cpu
         - mountPath: /rootfs/sys/devices/system/cpu/
           name: containers-cpu
           mountPropagation: Bidirectional
         - mountPath: /rootfs/sys/fs/cgroup/cpuset/kubepods/
           name: kubepods
         - mountPath: /var/lib/kubelet/device-plugins/
           name: checkpointfile
           readOnly: true
         - mountPath: /dev/dri
           name: dri-path
           readOnly: false
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
      volumes:
      - name: time-mount
        hostPath:
          path: /etc/localtime
      ## CPUSetter parses the Kubelet checkpoint file for Device allocations
      - name: checkpointfile
        hostPath:
         path: /var/lib/kubelet/device-plugins/
      - name: containers-cpu
        hostPath:
         path: /var/lib/kubelet/emulator/cpu/
      - name: system-cpu
        hostPath:
         path: /sys/devices/system/cpu/
      - name: kubepods
        hostPath:
         path: /sys/fs/cgroup/cpuset/kubepods/
      - name: dri-path
        hostPath:
          # directory location on host
          path: /dev/dri
      ## The pool configuration files need to be mounted here
      - name: cpu-pooler-config
        configMap:
          name: cpu-pooler-configmap
      serviceAccountName: cpu-setter
