---
apiVersion: v1
kind: Service
metadata:
  name: cpu-dev-pod-mutator-svc
  namespace: kube-system
  labels:
    app: cpu-dev-pod-mutator 
spec:
  ports:
  - name: webhook
    port: 443
  selector:
    app: cpu-dev-pod-mutator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-dev-pod-mutator-deployment
  namespace: kube-system
  labels:
    app: cpu-dev-pod-mutator
spec:
  selector:
    matchLabels:
      app: cpu-dev-pod-mutator
  replicas: 1
  template:
    metadata:
      name: cpu-dev-pod-mutator
      labels:
        app: cpu-dev-pod-mutator
    spec:
      containers:
        - name: cpu-dev-pod-mutator
          image: docker.io/library/cpu-device-webhook:latest
          args:
            - -tls-cert-file=/etc/webhook/certs/cert.pem
            - -tls-private-key-file=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: cpu-pooler-config
              mountPath: /etc/cpu-pooler
      nodeSelector:
         #node-role.kubernetes.io/master: ""
         kubernetes.io/hostname: bms-cp-1-000
      volumes:
        - name: webhook-certs
          secret:
            secretName: cpu-dev-webhook-secret
        - name: cpu-pooler-config
          configMap:
            name: cpu-pooler-configmap
